# Site
name: "Drishti"
title: "Drishti"
bio: ""  
logo: assets/images/logo-dark.png
logo-full: assets/images/logo-dark-full.png
favicon: assets/images/logo-dark.png
baseurl: 
google_analytics: G-577MRTS9CK
disqus: drishti-iitdh
# mailchimp-list: 
include: ["_pages"]
permalink: /:title/
email: drishti@iitdh.ac.in
instagram: drishti.iitdh
linkedin: drishti-iit-dharwad

# Team
team:
  subham:
    display_name: Subham Kumar
    short_name: Subham
    sub_role: Overall Coordinator, Journalist
    avatar: subham.jpg
    email: 200020047@iitdh.ac.in
    bio: Passionate journalist, avid traveler, and social advocate. Through my words, I uncover untold stories, highlight social issues, and inspire change. Join me on a journey to uncover untold stories, highlight social issues, and inspire change as we make a positive impact, one story at a time.
    instagram: kanwat_shubham
    twitter: shub6535
  om:
    display_name: Om Patil
    short_name: Om
    sub_role: Editor
    avatar: om.jpg
    email: 200010036@iitdh.ac.in
    web: https://modernoctave.github.io/
    instagram: om.s.patil
    linkedin: om-patil-032915204
    bio: Programmer, Roboticist, Linux Enthusiast, and an Aspiring ML Researcher but above all a journalist at heart!
  shahil:
    display_name: Shahil Patel
    short_name: Shahil
    sub_role: Designer
    avatar: shahil.jpg
    email: 200010039@iitdh.ac.in
    linkedin: shahil-patel-97298b1bb
    bio: A programming and graphic design enthusiast and experienced team leader, creating innovative solutions, leading graphic design projects, and crafting visually stunning designs.
  atharva:
    display_name: Atharva Virendra Tijare
    short_name: Atharva
    avatar: atharva.jpg
    email: atharvatijare04@gmail.com
    instagram: atharva.tijare
    linkedin: atharva-virendra-tijare-b0a926258
    bio: A passionate coder, exploring the endless possibilities of technology. With a unique blend of technical expertise and critical sense of art and design. Embracing innovation with elegance!
  sid:
    display_name: Siddhartha Prasad
    short_name: Sid
    sub_role: Team Lead
    avatar: siddhartha.jpg
    email: 210030033@iitdh.ac.in
    instagram: siddhartha_pd
    bio: From the passionate city of Patna, believes in humanity, science buff, loves to design and edit, and Gamer by birth.
  mahesh:
    display_name: Mahesh Krishnam
    short_name: Mahesh
    avatar: mahesh.webp
    email: 220120011@iitdh.ac.in
    instagram: krishnam_mahesh
    linkedin: mahesh-krishnam-a8a0b422b
    twitter: Krishnam_Mahesh
    bio: From Patna, Bihar. Exploring the infinite possibilities.
  yash:
    display_name: Yash Satish Kute 
    short_name: Yash
    avatar: yash.jpg
    email: yashkute762@gmail.com
    instagram: yash2805k
    linkedin: yash-kute-3714aa253
    bio: "Delivering captivating campus stories with wit and a unique perspective. Get ready to embark on an exciting journalistic journey through my insightful lens!"
  supriya:
    display_name: Supriya H
    short_name: Supriya
    sub_role: Team Lead
    avatar: supriya.jpg
    email: 210020054@iitdh.ac.in
    instagram: sup_27__
    linkedin: Supriya H
    bio: You can reach out to me anytime, I can be your voice.
  varshitha:
    display_name: Hema Varshitha Bandi
    short_name: Varshitha
    avatar: varshitha.jpg
    email: 210020005@iitdh.ac.in
    instagram: varshitha.bandi
    linkedin: Hema Varshitha Bandi
    bio: Enthusiastic about producing engaging and informative content.
  pushpa:
    display_name: Pushpa Parvathi Battina
    short_name: Pushpa
    sub_role: Team Lead
    avatar: pushpa.jpg
    email: 210010009@iitdh.ac.in
    instagram: pushpa_battina04
    linkedin: parvathi-battina
    bio: Passionate about writing and creating captivating and engaging content for the club.
  upo:
    display_name: Upakramanika
    short_name: Upo
    avatar: upo.png
    email: upakramanika@gmail.com
    instagram: _thequestionmark_
    linkedin: upakramanika-bishnu-339901254
    bio: A self taught digital artist with a keen interest in learning all about design.
  lavanya:
    display_name: Lavanya Shende
    short_name: Lavanya
    avatar: lavanya.jpg
    email: 220120022@iitdh.ac.in
    instagram: lavanya_shende
    linkedin: shende-lavanya-jayant-85a870258
    bio: Immersed in the captivating world of storytelling, I amplify the voices and stories on college campus.
  mukta:
    display_name: Mukta Vedpathak
    short_name: Mukta
    avatar: mukta.jpg
    bio: An amateur and avid writer, here to serve you all the crisp updates and stories around, with a pinch of creativity! 
    twitter: MuktaVedpathak
    instagram: _mukta_vedpathak_29
    email: muktavedpathak29@gmail.com
    linkedin: mukta-vedpathak-1152a8250
  deekshith:
    display_name: Deekshith Kumar
    short_name: Deekshith
    avatar: deekshith.jpg
    email: 220010039@iitdh.ac.in
    web: 
    instagram: https://www.instagram.com/deekshithpampati/
    linkedin: 
    bio: I'm all about humor and hard work. From delivering captivating narratives to infusing every situation with laughter, I'm your go-to journalist for a unique and engaging perspective.
  vikas:
    display_name: Vikas jain
    short_name: Vikas
    avatar: vikas.jpg
    email: 220120029@iitdh.ac.in
    web: 
    instagram: 
    linkedin: www.linkedin.com/in/vikasjain226
    bio: An AI and ML enthusiast turned journalist, driven by the mission to bring to light the untold stories hidden within campus life, ensuring that awareness reaches everyone.
  simoni:
    display_name: Simoni Tripathi
    short_name: Simoni
    avatar: simoni.jpg
    email: lilmonica26@gmail.com
    web: 
    instagram: https://instagram.com/simonitripathi?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D
    linkedin: https://www.linkedin.com/in/simoni-tripathi-035077268
    bio: I imagine lavender skies with white roses•.•
    twitter: moonmoniiiii
  yasaswini:
    display_name: Banavat Yasaswini
    short_name: Yasaswini
    avatar: yasaswini.jpg
    email: 220010010@iitdh.ac.in
    web: 
    instagram: yasaswini_srinivas3985
    linkedin: BANAVAT Yasaswini
    bio:  I believe in the power of storytelling to drive positive change and foster understanding. By presenting diverse perspectives and exploring multifaceted issues, I aim to inform and engage readers in meaningful conversations.
  riya:
    display_name: Riya Ninad Chitnis
    short_name: Riya
    avatar: riya.jpg
    email: riyanchitnis@gmail.com
    web: 
    instagram: 
    linkedin: 
    bio: Passionate about writing and eager to bring to you crisp content that speaks on its on accord
  aditi:
    display_name: Aditi Soukar
    short_name: Aditi
    avatar: aditi.jpg
    email: 220030001@iitdh.ac.in
    web: 
    instagram: instagram.com/aditisoukar
    linkedin: https://www.linkedin.com/in/aditi-soukar-833360250
    bio: I am a sports enthusiast here to write some content because I like typing on the keyboard and it's fun coming up with things to write.
    twitter: soukaraditi
  tushar:
    display_name: Tushar Moitra
    short_name: Tushar
    avatar: tushar.jpg
    email: tmoitra78@gmail.com
    web: 
    instagram: tachefied
    linkedin: 
    bio: Currently Pursuing BS in Interdisciplinary Sciences. Interested in AI-ML and the math behind it. I like writing poems and jamming with the guitar in my free time.
  namratha:
    display_name: Thella Namratha
    short_name: Namratha
    avatar: namratha.jpg
    email: ep23bt003.iitdh.ac.in
    web: 
    instagram: 
    linkedin: 
    bio: Always challenging myself to put the best out there. Highlighting various topics to reach a larger diaspora. Also, here to make all the content you read interesting and indulging.
    twitter: _kimie_kim
  aiswarya:
    display_name: Aiswarya M S
    short_name: Aiswarya
    avatar: aiswarya.jpg
    email: ee23bt055@iitdh.ac.in
    web: 
    instagram: I'm on Instagram as @_ams_221. Install the app to follow my photos and videos. https://www.instagram.com/invites/contact/?i=a7q2emqadw1g&utm_content=rwqbuj3
    linkedin: https://www.linkedin.com/in/aiswarya-m-s-217305285
    bio: Enthusiastic Designer, who tries to convey messages through the world of colors... Still who wants to explore more about  that beautiful world..
  preksha:
    display_name: Preksha Patange
    short_name: Preksha
    avatar: preksha.jpg
    email: mc23bt029@iitdh.ac.in
    web: 
    instagram: pprekshaa_05
    linkedin: 
    bio: A graphic design enthusiast.I like expressing thoughts through my art and designing.
  sakeena:
    display_name: Dodda Sakeena Sadhika 
    short_name: Sakeena
    avatar: sakeena.jpg
    email: 210010062@iitdh.ac.in
    web: 
    instagram: https://instagram.com/sakeena._.7?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D
    linkedin: https://www.linkedin.com/in/sakeena-dodda-b30b29245
    bio: Versatility is my strength and journalism makes me enthusiastic about it.So No longer wait let's delve into the untold narratives waiting to be discovered!!
  lalitha:
    display_name: Lalitha Tupakula
    short_name: Lalitha
    avatar: lalitha.jpg
    email: Is23bm039@iitdh.ac.in
    web: 
    instagram: https://instagram.com/lalithathupakula?utm_source=qr&igshid=NGExMmI2YTkyZg%3D%3D
    linkedin: https://www.linkedin.com/in/thupakula-lalitha-071b61289
    bio: Trying to quench my thirst of knowledge.
    twitter: LalithaTupakula
  aabha:
    display_name: Aabha Devnikar
    short_name: Aabha
    avatar: aabha.jpg
    email: ch23bt002@iitdh.ac.in 
    web: 
    instagram: https://instagram.com/aabha_2503?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D
    linkedin: https://www.linkedin.com/in/aabha-devnikar-b336a027a
    bio: Just an enthusiastic reader and writer craving for knowledge and adventures ...

# Roles
roles:
  - role: Chief Editors
    members:
      - subham
      - om
      - shahil
  - role: Editors
    members:
      - pushpa
      - varshitha
      - aditi
      - simoni
      - tushar
      - aabha
      - riya
      - namratha
  - role: Journalists
    members:
      - supriya
      - lavanya
      - sakeena
      - yasaswini
      - deekshith
      - vikas
      - lalitha
  - role: Designers
    members:
      - sid
      - atharva
      - mahesh
      - aiswarya
      - preksha
  - role: Public Relations
    members:
      - lavanya
      - sakeena
      - yash
      - aditi
      - deekshith
      - tushar
      - lalitha
      - yasaswini

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
